/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Noto Sans TC",
          "PingFang TC",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      borderRadius: {
        // 全站直角 — 任何 rounded-* 都退化成 0
        none: "0",
        sm: "0",
        DEFAULT: "0",
        md: "0",
        lg: "0",
        xl: "0",
        "2xl": "0",
        "3xl": "0",
        full: "0",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        "coffee-paper": {
          // 紙感米白 · light — 柔和對比,文字偏深焙咖啡而非純黑
          primary: "#3A2F26",
          "primary-content": "#FFF8EE",
          secondary: "#7A6A5C",
          "secondary-content": "#FFF8EE",
          accent: "#8A5A35",
          "accent-content": "#FFF8EE",
          neutral: "#3A2F26",
          "neutral-content": "#FFF8EE",
          "base-100": "#FFF8EE",
          "base-200": "#F8F3E9",
          "base-300": "#F4E9D8",
          "base-content": "#3A2F26",
          info: "#3B5F8A",
          success: "#4F7A3A",
          warning: "#A06B1E",
          error: "#8A2E2E",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--tab-radius": "0",
          "--animation-btn": "0s",
          "--animation-input": "0s",
          "--border-btn": "1px",
        },
      },
      {
        "coffee-roast": {
          // 深焙咖啡 · dark — 文字偏溫潤奶油色,降低眩光
          primary: "#E8DCC4",
          "primary-content": "#1B1714",
          secondary: "#9A8C7E",
          "secondary-content": "#1B1714",
          accent: "#C8975F",
          "accent-content": "#1B1714",
          neutral: "#2A2521",
          "neutral-content": "#E8DCC4",
          "base-100": "#1B1714",
          "base-200": "#211D1A",
          "base-300": "#2A2521",
          "base-content": "#D9CCB3",
          info: "#7FA6D9",
          success: "#8FB87A",
          warning: "#D9A26B",
          error: "#D97A7A",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--tab-radius": "0",
          "--animation-btn": "0s",
          "--animation-input": "0s",
          "--border-btn": "1px",
        },
      },
    ],
    darkTheme: "coffee-roast",
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
};
